services:

  newinnov-app:
    container_name: newinnov-app
    build: .
    restart: unless-stopped
    volumes:
      - ./api-app:/var/www/html
    ports:
      - 3021:80

  newinno_mysql_db:
    container_name: mysql_newinnov
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: newinnov_app
    # volumes:
    #   - ./backups:/home/backups
    restart: unless-stopped
    ports:
    - 3022:3306
  
  newinnov_phpmyadmin:
    container_name: phpmyadmin_newinnov
    image: phpmyadmin:5.2.1
    ports:
      - 8023:80
    environment:
      - PMA_ARBITRARY=1